spring.application.name=movie

#SQL
spring.profiles.active=mysql

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#//API for TMDB
tmdb.api.url=https://api.themoviedb.org/3
tmdb.api.key=${TMDB-API-KEY:}
tmdb.api.token=${TMDB-API-RAT:}
